import { useState, useRef } from 'react';
import { Megaphone, Send, Image, X, Sparkles, Wand2, Bot, Loader2, ChevronDown, ChevronUp } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import toast from 'react-hot-toast';
import api from '../api/axios';
import { useAuth } from '../context/AuthContext';

const CATEGORIES = [
  { label: 'General',      icon: '📋', active: 'bg-[#475569] text-white border-[#475569] ring-2 ring-[#475569]/20', color: 'border-[#cbd5e1] bg-white text-[#475569] hover:bg-[#f8fafc]' },
  { label: 'Event',        icon: '🎉', active: 'bg-[#059669] text-white border-[#059669] ring-2 ring-[#059669]/20', color: 'border-[#cbd5e1] bg-white text-[#475569] hover:bg-[#f8fafc]' },
  { label: 'Lost & Found', icon: '🔍', active: 'bg-[#d97706] text-white border-[#d97706] ring-2 ring-[#d97706]/20', color: 'border-[#fef3c7] bg-[#fffbeb] text-[#b45309] hover:bg-[#fffbeb]/80' },
  { label: 'Emergency',    icon: '🚨', active: 'bg-[#dc2626] text-white border-[#dc2626] ring-2 ring-[#dc2626]/20', color: 'border-[#fee2e2] bg-[#fef2f2] text-[#b91c1c] hover:bg-[#fef2f2]/80' },
];
const PRIORITIES = ['Low', 'Medium', 'High', 'Urgent'];
const MAX_CONTENT = 500;

export default function NoticeForm({ onCreated, defaultCategory }) {
  const { activeCommunityId } = useAuth();
  const navigate = useNavigate();
  const [title, setTitle] = useState('');
  const [content, setContent] = useState('');
  const [category, setCategory] = useState(defaultCategory || 'General');
  const [priority, setPriority] = useState(defaultCategory === 'Emergency' ? 'Urgent' : 'Medium');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [imageFile, setImageFile] = useState(null);
  const [imagePreview, setImagePreview] = useState(null);
  const [dragActive, setDragActive] = useState(false);
  const [mediaOpen, setMediaOpen] = useState(false);
  const fileInputRef = useRef(null);

  const [aiLoading, setAiLoading] = useState(null);
  const [generatePrompt, setGeneratePrompt] = useState('');
  const [showGenerateInput, setShowGenerateInput] = useState(false);

  const handleFileSelect = (file) => {
    if (file && file.type.startsWith('image/')) {
      if (file.size > 5 * 1024 * 1024) { toast.error('File size must be less than 5MB'); return; }
      setImageFile(file);
      setImagePreview(URL.createObjectURL(file));
      setMediaOpen(true);
    }
  };

  const handleDrag = (e) => {
    e.preventDefault(); e.stopPropagation();
    if (e.type === 'dragenter' || e.type === 'dragover') setDragActive(true);
    else if (e.type === 'dragleave') setDragActive(false);
  };

  const handleDrop = (e) => {
    e.preventDefault(); e.stopPropagation();
    setDragActive(false);
    if (e.dataTransfer.files?.[0]) handleFileSelect(e.dataTransfer.files[0]);
  };

  const removeImage = () => {
    setImageFile(null); setImagePreview(null);
    if (fileInputRef.current) fileInputRef.current.value = '';
  };

  const callAI = async (mode, extra = {}) => {
    setAiLoading(mode);
    try {
      const { data } = await api.post('/ai/notice-assist', { mode, title, content, category, ...extra });
      if (mode === 'generate') {
        if (data.title) setTitle(data.title);
        if (data.content) setContent(data.content);
        toast.success('Notice generated by AI ✨');
      } else {
        if (data.content) setContent(data.content);
        toast.success(mode === 'suggest' ? 'Details suggested by AI ✨' : 'Content improved by AI 🪄');
      }
    } catch (err) {
      toast.error(err.response?.data?.message || 'AI request failed');
    } finally {
      setAiLoading(null);
    }
  };

  const handleSuggest  = () => { if (!title.trim()) { toast.error('Enter a title first'); return; } callAI('suggest'); };
  const handleImprove  = () => { if (!content.trim()) { toast.error('Write some content first'); return; } callAI('improve'); };
  const handleGenerate = () => {
    if (!generatePrompt.trim()) { toast.error('Enter a short description'); return; }
    callAI('generate', { prompt: generatePrompt });
    setShowGenerateInput(false); setGeneratePrompt('');
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!activeCommunityId) { toast.error('Please select a community first'); navigate('/community'); return; }
    setError(''); setLoading(true);
    try {
      const formData = new FormData();
      formData.append('title', title);
      formData.append('content', content);
      formData.append('category', category);
      formData.append('priority', priority);
      formData.append('communityId', activeCommunityId);
      if (imageFile) formData.append('image', imageFile);

      const { data } = await api.post('/notices', formData, { headers: { 'Content-Type': 'multipart/form-data' } });

      setTitle(''); setContent(''); setCategory('General'); setPriority('Medium');
      setImageFile(null); setImagePreview(null);
      if (fileInputRef.current) fileInputRef.current.value = '';
      onCreated?.(data);
      toast.success(category === 'Emergency' ? 'Emergency notice posted' : 'Notice posted');
    } catch (err) {
      const message = err.response?.data?.message || 'Failed to post notice';
      setError(message); toast.error(message);
    } finally {
      setLoading(false);
    }
  };

  const contentCharsLeft = MAX_CONTENT - content.length;

  return (
    <form onSubmit={handleSubmit} className="relative overflow-hidden rounded-[20px] border border-[#e2e8f0] bg-white shadow-[0_1px_3px_rgba(0,0,0,0.02)] z-0">
      {/* Header */}
      <div className="flex items-center gap-3 border-b border-[#f1f5f9] px-5 py-4">
        <span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#0f172a] text-white shadow-xs">
          <Megaphone className="h-4 w-4" />
        </span>
        <div>
          <h2 className="text-base font-bold text-[#0f172a] leading-tight" style={{ fontFamily: '"Space Grotesk", sans-serif' }}>Post a Notice</h2>
          <p className="text-xs text-[#64748b]">Share updates with your neighbours</p>
        </div>
      </div>

      <div className="p-5 lg:p-6 space-y-5">
        {error && (
          <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-600">
            {error}
          </div>
        )}

        {/* Title */}
        <div>
          <label htmlFor="title" className="mb-1.5 block text-sm font-semibold text-[#334155]">Title</label>
          <input id="title" type="text" value={title} onChange={(e) => setTitle(e.target.value)}
            required placeholder="What's happening?" className="w-full rounded-xl border border-[#cbd5e1] bg-white px-4 py-3 text-sm text-[#0f172a] outline-none transition-all duration-150 placeholder:text-[#94a3b8] focus:border-[#0f172a]" />
        </div>

        {/* Category chips */}
        <div>
          <label className="mb-2 block text-sm font-semibold text-[#334155]">Category</label>
          <div className="flex flex-wrap gap-2">
            {CATEGORIES.map((cat) => (
              <button key={cat.label} type="button" onClick={() => {
                  setCategory(cat.label);
                  if (cat.label === 'Emergency') setPriority('Urgent');
                  else if (priority === 'Urgent') setPriority('Medium');
                }}
                className={`inline-flex items-center gap-1.5 rounded-xl border px-3.5 py-2 text-xs font-bold transition-all duration-150 hover:-translate-y-0.5 ${
                  category === cat.label ? cat.active : cat.color
                }`}>
                <span>{cat.icon}</span>
                {cat.label}
              </button>
            ))}
          </div>
        </div>

        {/* Priority */}
        <div>
          <label htmlFor="priority" className="mb-1.5 block text-sm font-semibold text-[#334155]">Priority</label>
          <select id="priority" value={priority} onChange={(e) => setPriority(e.target.value)} className="w-full rounded-xl border border-[#cbd5e1] bg-white px-4 py-3 text-sm text-[#0f172a] outline-none transition-all duration-150 focus:border-[#0f172a]">
            {PRIORITIES.map((level) => <option key={level} value={level}>{level}</option>)}
          </select>
        </div>

        {/* Details with AI toolbar + char counter */}
        <div>
          <div className="mb-2 flex items-center justify-between gap-2 flex-wrap">
            <label htmlFor="content" className="text-sm font-semibold text-[#334155]">Details</label>
            
            {/* AI Assistant Toolbar */}
            <div className="flex items-center gap-1 rounded-xl border border-[#e2e8f0] bg-[#f8fafc] p-1 shadow-xs">
              <button type="button" onClick={handleSuggest} disabled={!!aiLoading} title="AI Suggest Details"
                className="flex items-center gap-1.5 rounded-lg bg-white border border-[#e2e8f0]/80 px-2.5 py-1.5 text-xs font-bold text-[#0f172a] transition-all hover:bg-[#f1f5f9] disabled:opacity-50">
                {aiLoading === 'suggest' ? <Loader2 className="h-3.5 w-3.5 animate-spin text-[#4f46e5]" /> : <Sparkles className="h-3.5 w-3.5 text-[#4f46e5]" />}
                Suggest
              </button>
              <button type="button" onClick={handleImprove} disabled={!!aiLoading} title="AI Improve content"
                className="flex items-center gap-1.5 rounded-lg bg-white border border-[#e2e8f0]/80 px-2.5 py-1.5 text-xs font-bold text-[#0f172a] transition-all hover:bg-[#f1f5f9] disabled:opacity-50">
                {aiLoading === 'improve' ? <Loader2 className="h-3.5 w-3.5 animate-spin text-[#0284c7]" /> : <Wand2 className="h-3.5 w-3.5 text-[#0284c7]" />}
                Improve
              </button>
              <button type="button" onClick={() => setShowGenerateInput((v) => !v)} disabled={!!aiLoading} title="AI Prompt Generation"
                className="flex items-center gap-1.5 rounded-lg bg-white border border-[#e2e8f0]/80 px-2.5 py-1.5 text-xs font-bold text-[#0f172a] transition-all hover:bg-[#f1f5f9] disabled:opacity-50">
                {aiLoading === 'generate' ? <Loader2 className="h-3.5 w-3.5 animate-spin text-[#059669]" /> : <Bot className="h-3.5 w-3.5 text-[#059669]" />}
                Generate
              </button>
            </div>
          </div>

          {showGenerateInput && (
            <div className="mb-2.5 flex items-center gap-2 rounded-xl border border-[#cbd5e1] bg-[#f8fafc] p-2.5">
              <Bot className="h-4 w-4 shrink-0 text-[#475569]" />
              <input type="text" value={generatePrompt} onChange={(e) => setGeneratePrompt(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && (e.preventDefault(), handleGenerate())}
                placeholder="Describe your notice in a few words…"
                className="flex-1 bg-transparent text-sm text-[#0f172a] outline-none placeholder-[#94a3b8]" autoFocus />
              <button type="button" onClick={handleGenerate} disabled={aiLoading === 'generate'}
                className="flex items-center gap-1 rounded-lg bg-[#0f172a] px-3 py-1.5 text-xs font-bold text-white transition hover:bg-[#1e293b] disabled:opacity-60">
                {aiLoading === 'generate' ? <Loader2 className="h-3 w-3 animate-spin" /> : 'Go'}
              </button>
              <button type="button" onClick={() => { setShowGenerateInput(false); setGeneratePrompt(''); }}
                className="text-[#64748b] hover:text-[#0f172a]">
                <X className="h-4 w-4" />
              </button>
            </div>
          )}

          <textarea id="content" value={content} onChange={(e) => setContent(e.target.value.slice(0, MAX_CONTENT))}
            required rows={4} placeholder="Share the details with your neighbours…" className="w-full rounded-xl border border-[#cbd5e1] bg-white px-4 py-3 text-sm text-[#0f172a] outline-none transition-all duration-150 placeholder:text-[#94a3b8] focus:border-[#0f172a] resize-none" />

          {/* Character counter */}
          <div className="mt-1 flex justify-end">
            <span className={`text-xs font-medium tabular-nums ${
              contentCharsLeft <= 50 ? 'text-[#b91c1c]'
              : contentCharsLeft <= 100 ? 'text-[#d97706]'
              : 'text-[#64748b]'
            }`}>
              {content.length} / {MAX_CONTENT}
            </span>
          </div>
        </div>

        {/* Collapsible Optional Media upload dropdown */}
        <div className="border-t border-[#f1f5f9] pt-4">
          <button
            type="button"
            onClick={() => setMediaOpen(!mediaOpen)}
            className="flex w-full items-center justify-between text-sm font-semibold text-[#475569] hover:text-[#0f172a] transition-colors"
          >
            <span className="flex items-center gap-2">
              <Image className="h-4 w-4 text-[#64748b]" />
              Add Media
              <span className="text-xs font-normal text-[#94a3b8]">(Optional)</span>
              {imageFile && <span className="h-1.5 w-1.5 rounded-full bg-[#10b981]" />}
            </span>
            {mediaOpen ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
          </button>

          {mediaOpen && (
            <div className="mt-3 relative cursor-pointer rounded-xl border-2 border-dashed transition-all duration-200 animate-fade-in border-[#cbd5e1] bg-white hover:border-[#0f172a] hover:bg-[#f8fafc]"
              onDragEnter={handleDrag} onDragLeave={handleDrag} onDragOver={handleDrag} onDrop={handleDrop}
              onClick={() => fileInputRef.current?.click()}>
              <input ref={fileInputRef} type="file" accept="image/*" onChange={(e) => { if (e.target.files?.[0]) handleFileSelect(e.target.files[0]); }} className="hidden" />
              {imagePreview ? (
                <div className="relative p-2" onClick={(e) => e.stopPropagation()}>
                  <img src={imagePreview} alt="Preview" className="h-48 w-full rounded-lg object-cover shadow-sm" />
                  <button type="button" onClick={removeImage}
                    className="absolute right-4 top-4 flex h-8 w-8 items-center justify-center rounded-full bg-slate-900/60 text-white backdrop-blur-sm transition hover:bg-slate-900/80">
                    <X className="h-4 w-4" />
                  </button>
                  <div className="absolute bottom-4 left-4 rounded-lg bg-slate-900/60 px-3 py-1.5 text-xs font-medium text-white backdrop-blur-sm">
                    {imageFile?.name} ({(imageFile?.size / 1024 / 1024).toFixed(2)} MB)
                  </div>
                </div>
              ) : (
                <div className="flex flex-col items-center justify-center py-8">
                  <div className="mb-3 flex h-12 w-12 items-center justify-center rounded-full bg-white shadow-xs ring-1 ring-slate-100">
                    <Image className="h-5 w-5 text-[#475569]" />
                  </div>
                  <p className="text-sm font-semibold text-[#0f172a]">Click or drag to upload</p>
                  <p className="mt-0.5 text-xs text-[#64748b]">PNG, JPG, GIF · max 5 MB</p>
                </div>
              )}
            </div>
          )}
        </div>

        {/* Submit */}
        <button type="submit" disabled={loading}
          className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#0f172a] py-3 text-sm font-bold text-white shadow-sm transition-all duration-150 hover:bg-[#1e293b] disabled:opacity-60">
          <Send className="h-4 w-4" />
          {loading ? 'Posting…' : 'Post Notice'}
        </button>
      </div>
    </form>
  );
}
